### ISSUE TITLE
improve error message if oranda is run on a project version that does not yet have a github release

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#189]
if you:

0. configure your project to use cargo-dist
1. bump version of project locally
2. run oranda

you will get a gross error that from what i can tell is a parse error 
we can improve on this and it's important because it will be something people likely hit a bunch until we smooth out the dist->oranda exp some more

**Comment by zkat** [comment]
I came here to post about this, but also, I think there's an additional corner-case:

`cargo-release` typically does this (imo annoying) thing where it bumps your package's version to the next prerelease and tags that, and I think what I'm running into when `"cargo_dist": true` is set is that oranda looks at my Cargo.toml, sees the weird `0.2.1-alpha.0` version generated by `cargo-release`, and just... shits the bed. Improving the error message would be good, but I'm not sure what the best way is to tell the oranda action to target the _actual_ latest release.

**Comment by zkat** [comment]
hold that thought, this might be because I had an old cargo-release version. sigh!

**Comment by zkat** [comment]
yeah no, it's still happening :/

**Comment by ashleygwilliams** [comment]
hey @zkat - so i am not the hugest fan of cargo-release so i'm not as familiar with the workflow there. i suspect that part of what we are discussing here is actually stability channels heh :) from what i can tell this is the current workflow and i have a few questions what you'd want to see:

1. have a project released at 0.2.0, am working on developing 0.2.1
Q: while in "dev"/"prerelease mode" do you want oranda to show the latest "stable" version or the most recent pre-release (or both, but in different parts of the site)
2. cargo-release bumps your project to 0.2.1-prerelease.0 (i am still not entirely clear on this behavior)
Q: it sounds like you want oranda to continue showing and working for 0.2.0?

my suspicion here is that we can infer "stability channels" and have oranda continue to only release the latest "stable" channel release (aka version number with no extra annotations like alpha or prerelease) and then come up with another way to display other channels and more early release assets/installer.

the first naive pass at this to fetch the latest release from gh releases and not try to match it to the current Cargo.toml, which is probably a better move anyways.

i'm still not *100%* sure on the cargo-release workflow but we should definitely make sure that oranda can "handle" stuff it does (so long as it preserves the exp for folks who don't use it.)

thanks for trying stuff out and please continue to file/comment on issues! your feedback is super appreciated 🖤

**Comment by Gankra** [comment]
see https://github.com/axodotdev/cargo-dist/pull/167 :)

**Comment by zkat** [comment]
So from more testing, it turns out that the annoying `0.2.1-prerelease.0` dance is something an _old_ version of cargo-release was doing, and I think it still supports that, but it is definitely not the default anymore.

After messing around with cargo-dist and cargo-release for a while, I finally got things deploying "right", and at first, oranda didn't seem to work. But I tried it just now and it worked just fine? I was getting the json parse error before, I was sure, but I can't reproduce it anymore. I must've just been in a weird state while figuring stuff out.

Anyway, I'm excited about oranda (and cargo-dist), and it's been nice using them so far, even though I know both projects are _extremely_ young. They're still perfectly usable!
