### ISSUE TITLE
Support stripping first Markdown headers

### ISSUE THREAD

**Issue by manyinsects** [axodotdev/oranda#323]
Some projects usually have `# project name` as the first line of their README.md. If Oranda processes this as is, it looks like this:

![CleanShot 2023-05-17 at 16 53 44@2x](https://github.com/axodotdev/oranda/assets/6445316/3fe51311-c283-4983-87bb-05cd9c6015f7)

Seems very redundant, might be nice if we could automatically strip the first header if it includes the project name.

**Comment by ashleygwilliams** [comment]
so! there is a class called `oranda-hide` you can use to remove it- see https://raw.githubusercontent.com/axodotdev/oranda/main/README.md

**Comment by manyinsects** [comment]
ah beautiful, the more you know

**Comment by ashleygwilliams** [comment]
adding some context: when i worked at npm we originally had some logic to try to remove the first header (the logic was as naive as dropping the first line at some point) for rendering the readme on the package page, but it turns out this can be quite fraught and have horrible consequences if we "guess" wrong, and so enabling end user to do it if they want in a way that doesn't disrupt the readme rendering on github seemed like the best move, but we should probably advertise this more since you are 100% correct that basically everyone will have this issue
