### ISSUE TITLE
Funding is not detected

### ISSUE THREAD

**Issue by marcoieni** [axodotdev/oranda#389]
With [this](https://github.com/MarcoIeni/release-plz/pull/826/commits/f8ff146bd00d969d69a16287f1d46cea37ac7d0e) configuration, oranda doesn't detect funding.
![image](https://github.com/axodotdev/oranda/assets/11428655/a56f2991-9244-45dd-8e26-173b12d533e9)

I ran `oranda build && oranda serve` from the `/crates/release_plz` directory.
I tried running oranda from the root directory of the project specifying `--project-root` and/or `--config-path` but none of them worked. 
I also tried adding `"funding": true,` to the config file.

**Comment by ashleygwilliams** [comment]
hey @MarcoIeni - thanks for filing and i'm excited to see you using oranda- because your project is in a workspace, i think it's not finding the file the way it should. i can open a PR to let you configure the path to funding.yml as a backstop until we improve the support for workspaces- how does that sound?

by the way- we have a discord if you want to chat there! https://discord.gg/5m7tqr2eGr

**Comment by marcoieni** [comment]
> how does that sound?

sounds good, thanks! :)

**Comment by ashleygwilliams** [comment]
hey @MarcoIeni - got a PR for this at https://github.com/axodotdev/oranda/pull/391, gonna test on your repo to make sure it works :)
