### ISSUE TITLE
Any way to not depend on `libssl.so.1.1`?

### ISSUE THREAD

**Issue by geelen** [axodotdev/oranda#514]
Love the idea of this project, and tried standing it up on Cloudflare Pages with the simplest possible build config:

<img width="689" alt="image" src="https://github.com/axodotdev/oranda/assets/23264/1bd13bb4-3af0-4a3b-9e7f-dff7f8ab49bd">

But hitting the following runtime error:

```
/opt/buildhome/repo/node_modules/.pnpm/binary-install@1.1.0/node_modules/binary-install/node_modules/.bin/oranda: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I'm using the [beta build image](https://blog.cloudflare.com/moderizing-cloudflare-pages-builds-toolbox/) so I've got an internal thread going to see if we should add `libssl-dev` or something into that, but it occurred to me that I'm not clear why running `oranda build` should depend on `libssl` at all?

FWIW, _installing_ it works fine, it's only running the build that breaks. And it's nothing specific to NPM as far as I can tell, using the shell script downloading the binary has the same result.

**Comment by ashleygwilliams** [comment]
oh interesting! we have successfully published a bunch of oranda pages to CF pages but we do the build on GH actions and then use wrangler to upload. so if you want to try that in the meantime, i know it works :)

re: fixing the deps of binstall - this is a lib we don't own but i know the maintainer well and so i will see if we can't figure out a solution. that being said - it's there to avoid dynamically linking openssl which is also not great and so it's useful.

oranda build (for many configurations, but not all) makes network fetches to github to get data and metadata related to your releases- so that's why we have an ssl dependency. that being said- binstall is only called on install and so i think it's throwing up on install, not on build (npx still installs, just cleans up after itself). though you are saying it throws up on build and not install, which makes the error message confusing to me.

apropos of nothing - we have a discord if you wanna do any realtime debugging with me over there ;)  https://discord.gg/5m7tqr2eGr

**Comment by geelen** [comment]
Will jump in the discord, but just to clarify, if I move the `@axodotdev/oranda` dependency into package.json and change my build command to just `pnpm oranda build`, then I get this section of the build log at install time:

```
.../node_modules/@axodotdev/oranda postinstall$ node ./install.js
Progress: resolved 90, reused 0, downloaded 90, added 90, done
.../node_modules/@axodotdev/oranda postinstall: Downloading release from https://github.com/axodotdev/oranda/releases/download/v0.1.0/oranda-x86_64-unknown-linux-gnu.tar.gz
.../node_modules/@axodotdev/oranda postinstall: oranda has been installed!
.../node_modules/@axodotdev/oranda postinstall: Done
```

But it fails to build:

```
Executing user command: pnpm oranda build
/opt/buildhome/repo/node_modules/.pnpm/binary-install@1.1.0/node_modules/binary-install/node_modules/.bin/oranda: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by ashleygwilliams** [comment]
it was discovered that we removed our dependency on openssl in our asset fetch library axoasset, but we had failed to update it in oranda. i'll be updating that dep shortly and we'll cut a point release, which should fix this issue!
