### ISSUE TITLE
`build.rs` having the side effect of downloading tailwind CSS binary without user consent

### ISSUE THREAD

**Issue by simonsan** [axodotdev/oranda#603]
While I understand that you might want to use the Tailwind CSS CLI, I would find it a better approach to do that at runtime and not at build time. So when a potential user can agree to downloading a 3rd party binary. I was a bit shocked getting a warning from my firewall that a compiled build script wants to connect to the internet when I tried upgrading oranda.

I also looked through the releases and didn't find anything explicitly and in huge letters stating, that oranda will from this version on having a build script downloading third party binaries without my consent.

Please rethink your strategy here, I would appreciate it as a user of your software, if you would take the approach of delaying that process until oranda has been built and ask the user for permission to download.

Thank you! 🚀

**Comment by simonsan** [comment]
### Mildly related quote:

This is basic supply-chain security ... and a lot about trust when it's lost

Given this change was never done in a manner that ensured

 0) .. **reasonable disclosure / informed opt-in** of this fact

 1) .. **reproducible builds** were possible / straightforward

 2) .. **auditability** and fitness into existing build workflows beforehand breaking them

 3) .. **development** environment now running non-auditable/reproducible binaries

 4) .. **opt-out** mechanism that would mitigate above

This exposes potentially the `time` development environment to unaudited binaries creating uncertainty at the development stage

Even if someone for once makes auditable / reproducible build it will take long time until this gets into the tooling given wide ecosystem.

This change flew through unnoticed - granted https://crates.io/crates/cackle gave a heads-up 

It was easy to be naive when it was not properly documented though.

Many FOSS things require informed "non-free" or so opt-in - not by default - mechanism to binary blobs

Using precompiled binaries at libraries is IMO not the way to go and I am glad time made the choice of not opting into the bins.

This isn't just a security issue but this is a build issue that was supposed to be "Experiment" given changelog.

Does that tell anyone about opting into something knowingly ? I don't think so.

Besides that it takes agency away and this was done silently in the supply-chain.

We should not be operating at reverse-engineering binaries level or changing my workflows to audit any upstream code changes.

The code-changes as per current workflows are designed for source-level changes and not running binary-level reproducible builds.

Sorry but until the system evolves - these kind of changes should not be pushed like this and anyone is welcome to opt-out.

And by opting out,

`time` will save their contributors and their environments from exposure of the non-audited changing binary dependencies.

Let's keep in mind that people have different build & development environments.

And the fact that it is reversible and temporary which can be relaxed after this has been vetted and ironed out.

So needless to say I am woting :+1:

_Originally posted by @pinkforest in https://github.com/time-rs/time/discussions/611#discussioncomment-6772963_

**Comment by ashleygwilliams** [comment]
hi @simonsan! thanks so much for filing this issue and for being an oranda user. we'd love to hear more about how you are using oranda if you'd be willing to share!

i know that the issue of binary downloads is having a moment in the Rust ecosystem and appreciate you sharing your concerns about how oranda installs binaries.

a little bit of background about how oranda uses the binary download and why: oranda generates CSS that is shipped as a static file with the binary distributions that we build. this is because our end users generally do not edit or otherwise use tailwind to generate css- they use oranda so they don't have to worry about css. this started posing an issue for local development because local builds would potentially use stale css from the last release and not the css that was currently on main, which led to a confusing and frustrating experience for contributors. we originally had an env var to point to a local version of the css and required that contributors install a node environment and then run yarn or npm in a separate process. this was prohibitive for many and we want to keep the barrier of entry to contributing to our project low so more folks can be empowered to contribute.

we discussed as a team and decided that we would install a binary version of the tailwind cli during local development (on cargo build) so that folks working locally could use the css source on main instead of a potentially stale css from a previous release.

what's unfortunate is that cargo does not give us a way to separate cargo builds that happen during local development and the cargo builds that happen when folks `cargo install` our tool. we generally consider `cargo install`ing oranda to be a less-good installation option as we offer several pre-built binary and other package manager distributions, which will save users time and offer the best developer experience; but we know that even with that, it is sometimes still required that folks cargo install.

there are a few options for you and a few things for us out of this:

- we are happy to update the documentation to state explicitly that running a cargo build will install the tailwind cli
- we can plan ways to improve this to let folks opt-out of this installation, including a `--no-install` flag and/or an interactive prompt, as you suggest
- if you do not want the tailwind cli to be installed while you use oranda, you can use another distribution method that doesn't invoke a cargo build. if none of the options we have work for you, let us know and we can consider providing one that does!

i'd love to hear your thoughts and concerns, but would kindly ask that you refrain from cutting and pasting other folks comments from other threads. i understand and empathize with why you may feel it is helpful to do so, but i think it muddies and confuses the conversation. the use of binaries in libraries and the use of binaries in applications (binary projects) is different, and while i am happy to hear your concerns, it will be easiest for us to address them if we focus on the specific situation in oranda, and not other, potentially very different, projects.

**Comment by ashleygwilliams** [comment]
i am going to close this issue for now. feel free to follow up with any further comments, @simonsan.

**Comment by simonsan** [comment]
> what's unfortunate is that cargo does not give us a way to separate cargo builds that happen during local development and the cargo builds that happen when folks `cargo install` our tool. we generally consider `cargo install`ing oranda to be a less-good installation option as we offer several pre-built binary and other package manager distributions, which will save users time and offer the best developer experience; but we know that even with that, it is sometimes still required that folks cargo install.

>  * we can plan ways to improve this to let folks opt-out of this installation, including a `--no-install` flag and/or an interactive prompt, as you suggest

I would personally appreciate an **opt-in**, rather than an **opt-out**. As a responsible person/user, I need to say that **opt-out** is bad UX in almost every case you can make.

`cargo install`/`cargo install-update` are really valuable parts of the Rust ecosystem. I think it's a misconception, that only Rust developers for a tool, would install/build it this way. Therefore, I think it's more beneficial, to maybe check in your `build.rs` for something like `is ORANDA_DEV_INSTALL==true` or equally.

```rust
if env::var("ORANDA_DEV_INSTALL").is_ok() {
    // run binary install for developers only
}
```

> * if you do not want the tailwind cli to be installed while you use oranda, you can use another distribution method that doesn't invoke a cargo build. if none of the options we have work for you, let us know and we can consider providing one that does!

I'm usually pretty happy with my `cargo install`/`cargo install-updates`, so I would prefer not to use another. For things that I don't want to build, I prefer using `scoop` on Windows.

**Comment by simonsan** [comment]
Adding `oranda` in ScoopInstaller/Extras#11780

**Comment by ashleygwilliams** [comment]
since we don't currently have a way to update the scoop installer automatically, it's not clear to me that it's a good idea to add that quite yet (oranda is actively developed and releases frequently enough that manually updating is going to be unpleasant). i would appreciate if you let us take that on when we're ready to support it! we would be very interested in adding scoop support to cargo-dist, which we use to distribute our tools. we've just recently added homebrew support and so scoop would make quite a bit of sense. if you'd like to help contribute, that's a great place to start.

to make sure my previous point was clear: tailwind is not a runtime dependency of oranda. we would not want to prompt scoop users to install tailwind. oranda users should not install tailwind in almost all cases. the tailwind install is *only* important for local development. if you pursue the scoop PR (we'd rather you not for now!) please remove that dependency, as it would not work (oranda will not use a local tailwind), and it would not be useful (oranda only uses tailwind when building, and not at runtime, where it makes use of the pre-built static css).

as a long time rust core team member, team leader, and community member i am familiar with `cargo install` being an important part of the ecosystem. i also believe that the way it handles binary applications is confusing and wasteful, and there are many others who agree with me (and are similarly building tools to help improve the situation, as we are). i feel pretty strongly that it's a better, more consistent end user experience to install a pre-built binary. at the very least, it is cheaper (both $ and energy). the team will consider designing a different way to manage the tailwind dependency as i mentioned, but we are not currently prioritizing it as we are much more interested in getting people to use other install methods.

**Comment by simonsan** [comment]
`scoop` automatically updates the version due to the `autoupdate` and `checkver` fields. No need for manual intervention. ;)

**Comment by ashleygwilliams** [comment]
oh! well that's super cool and alleviates my concern there. thanks for letting me know- i do not know much about scoop 😅

**Comment by simonsan** [comment]
Removed tailwind from suggestions, and now it works, just waiting for review. When merged, people can install it with:

```sh
scoop bucket add extras
scoop install oranda
```

and update:
```sh
scoop update oranda
```

**Beware**: When `oranda` gains more traction, as in more stars on Github, the manifest can be moved to [ScoopInstaller/Main](https://github.com/ScoopInstaller/Main) as their criteria state:

> a GitHub project, it should have at least 500 stars and 150 forks

Hence for now it is in [ScoopInstaller/Extras](https://github.com/ScoopInstaller/Extras).

**Comment by ashleygwilliams** [comment]
that's pretty awesome @simonsan - thank you very much. if you'd like, we'd welcome an addition to oranda's own oranda.json so that we can advertise this new method: https://github.com/axodotdev/oranda/blob/main/oranda.json#L24. Let me know if you'd like to (you deserve the credit!), otherwise I'll add it tomorrow :)

**Comment by simonsan** [comment]
> that's pretty awesome @simonsan - thank you very much. if you'd like, we'd welcome an addition to oranda's own oranda.json so that we can advertise this new method: https://github.com/axodotdev/oranda/blob/main/oranda.json#L24. Let me know if you'd like to (you deserve the credit!), otherwise I'll add it tomorrow :)

Feel free to add ;) Will probably be something along the lines of:
`scoop bucket add extras; scoop install oranda` as you really need both steps for now if you have installed `scoop`.

Ah, and it might take a few days to get merged. So I'll link it, so you can see when it's merged.

**Comment by simonsan** [comment]
@ashleygwilliams When it comes to crates.io distribution these seem to be relevant here though:

- [CWE-829: Inclusion of Functionality from Untrusted Control Sphere](https://cwe.mitre.org/data/definitions/829.html)
The product imports, requires, or includes executable functionality (such as a library) from a source that is outside the intended control sphere.

- [CWE-494: Download of Code Without Integrity Check](https://cwe.mitre.org/data/definitions/494.html)
The product downloads source code or an executable from a remote location and executes the code without sufficiently verifying the origin and integrity of the code.

Came up in a discussion here: https://github.com/rustsec/advisory-db/issues/1737#issuecomment-1685159078

So while I'm switching to another distribution channel now, making the information more clear (e.g. in a future release note) or changing the way the CLI binary is pulled in, is still useful. Should I open a tracking issue for that?

EDIT: Regarding CWE-494:
They don't distribute hashes with their binaries, so I opened tailwindlabs/tailwindcss#11888

**Comment by simonsan** [comment]
@ashleygwilliams Works! 👍🏽 

![2023-08-24 20_20_05-oranda_ Add version 0 3 1 by simonsan · Pull Request #11780 · ScoopInstaller_Ext](https://github.com/axodotdev/oranda/assets/14062932/00263cc5-fdf2-4132-9eb4-e5a6d2c82a88)

**Comment by hawkw** [comment]
I've opened #609, which changes the `oranda-generate-css` crate to attempt to use a pre-existing `tailwindcss` binary if it exists on the `PATH`, and only downloads the pre-compiled CLI binary if it isn't already present on the system. The `tailwindcss` CLI is still a build-time dependency, but the download can be avoided if the user has already installed Tailwind, e.g. from their package manager.
