### ISSUE TITLE
draft mdBook chapter titles are unreadable in `oranda-dark` and `oranda-light` mdBook theme

### ISSUE THREAD

**Issue by hawkw** [axodotdev/oranda#654]
mdBook has a concept of "draft chapters", where the chapter name appears in the table of contents but no page actually exists for that chapter. these chapter titles are greyed out in the table of contents. when rendering a mdBook using Oranda, the default `oranda-dark` and `oranda-light` themes color the the names of these draft chapters the same as the background color, rendering them unreadable. 

with all other mdBook themes provided by Oranda, the draft chapter titles are basically readable. for example, with the mdBook "navy" theme, they look like this:
![image](https://github.com/axodotdev/oranda/assets/2796466/f08d3570-ef2d-4e14-881d-4a044e7c0de8)

with the `oranda-dark` theme, though, the draft chapter titles are the same as the background:
![image](https://github.com/axodotdev/oranda/assets/2796466/6821462d-3b06-42fb-9b21-08b70f61272d)

and similarly, with the `oranda-light` theme, they are white (as is the background):
![image](https://github.com/axodotdev/oranda/assets/2796466/02eac7ec-8622-4d22-b8a3-d7a15afed2c8)

**Comment by manyinsects** [comment]
Good call, this also came up on Discord, I think.

**Comment by 06chaynes** [comment]
This is probably too naive a solution for this but thought I would throw the idea out.

In `oranda-css/mdbook-theme/css/chrome.css`: 
```css
.chapter li.chapter-item div {
    color: var(--sidebar-fg);
    filter: brightness(70%);
}
```
Produces:
<img width="186" alt="Screenshot 2023-10-05 at 2 44 50 PM" src="https://github.com/axodotdev/oranda/assets/612378/a540cd85-7a5a-4df6-8154-055971ec149d">

I haven't noticed any unintended side effects from this yet but haven't checked all the themes or what not.

JIC this is acceptable I opened PR #655, feel free to close if otherwise though!
